project:
  type: website
  output-dir: _site
  pre-render:
    - quarto typst compile resume.typ
  render:
    - "*.qmd"
    - "posts/**/*.qmd"
  resources:
    - "assets/favicon/**"
    - resume.pdf

website:
  # title: "Ishaat Chowdhury" # Intentionally not set
  site-url: "https://www.ishaat.ca"
  favicon: assets/favicon/favicon.ico
  open-graph:
    site-name: "Ishaat Chowdhury"
  twitter-card: true
  navbar:
    title: "Ishaat Chowdhury"
    right:
      - about.qmd
      - text: Resume
        href: resume.pdf
      - icon: rss
        href: index.xml
  page-footer:
    center: "© 2025 Ishaat Chowdhury"
    right:
      - icon: github
        href: https://github.com/ishchow/personal-site
        aria-label: Source Code
      - icon: linkedin
        href: https://ca.linkedin.com/in/ishaatc
        aria-label: LinkedIn
      - icon: envelope
        href: mailto:ishaatchowdhury@gmail.com
        aria-label: Email

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    include-in-header: assets/favicon/head.html
